services:
  rpc_proxy:
    container_name: rpc_proxy
    image: rpc_proxy
    build:
      context: .
    restart: always
    environment:
      - CONFIG_FILE=/config.json
    volumes:
      - './config.json:/config.json:ro'
    ports:
      - '127.0.0.1:8544:8544'
